name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 5 * * 3'

jobs:
  build_python:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ]
    name: "Build python:${{ matrix.python_version}}"
    env:
      FULL_IMAGE_NAME: "ghcr.io/${{ github.repository }}/python"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          podman build --file python/Dockerfile \
            --tag ${FULL_IMAGE_NAME}:${{ matrix.python_version }} \
            --build-arg PYTHON_VERSION=${{ matrix.python_version }} \
            --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          podman login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          podman push ${FULL_IMAGE_NAME}:${{ matrix.python_version }}

  build_java:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java_version: [ '17', '21' ]
    name: "Build java-maven:${{ matrix.java_version}}"
    env:
      FULL_IMAGE_NAME: "ghcr.io/${{ github.repository }}/java-maven"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          podman build --file java-maven/Dockerfile \
            --tag ${FULL_IMAGE_NAME}:${{ matrix.java_version }} \
            --build-arg JAVA_VERSION=${{ matrix.java_version }} \
            --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          podman login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          podman push ${FULL_IMAGE_NAME}:${{ matrix.java_version }}

  build_shellcheck:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        shellcheck_version: [ '0.10.0' ]
    name: "Build shellcheck:${{ matrix.shellcheck_version}}"
    env:
      FULL_IMAGE_NAME: "ghcr.io/${{ github.repository }}/shellcheck"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          podman build --file shellcheck/Dockerfile \
            --tag ${FULL_IMAGE_NAME}:${{ matrix.shellcheck_version }} \
            --build-arg SHELLCHECK_VERSION=${{ matrix.shellcheck_version }} \
            --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          podman login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          podman push ${FULL_IMAGE_NAME}:${{ matrix.shellcheck_version }}

  build_clangformat:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        clangformat_version: [ '14.0.6', '16.0.6', '17.0.6', '18.1.8', '19.1.4' ]
    name: "Build clang-format:${{ matrix.clangformat_version}}"
    env:
      FULL_IMAGE_NAME: "ghcr.io/${{ github.repository }}/clang-format"
      FULL_VERSION: "${{ matrix.clangformat_version }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          podman build --file clang-format/Dockerfile \
            --tag ${FULL_IMAGE_NAME}:${FULL_VERSION%%.*} \
            --build-arg CLANGFORMAT_VERSION=${{ matrix.clangformat_version }} \
            --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}"
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          podman login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          podman push ${FULL_IMAGE_NAME}:${FULL_VERSION%%.*}

  hadolint:
    runs-on: ubuntu-24.04
    name: "Hadolint"
    steps:
      - uses: actions/checkout@main
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
