name: ci

on:
  push:
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.10' ]
    name: "Build python:${{ matrix.python_version}}"
    env:
      FULL_IMAGE_NAME: "ghcr.io/${{ github.repository }}/python"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          podman build --file python/Dockerfile --tag ${FULL_IMAGE_NAME}:${{ matrix.python_version }} \
            --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}"